name: Windows Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github\workflows\requirements.txt

      - name: Set up Java 11 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'

      - name: Install hiptest-publisher gem
        run: gem install hiptest-publisher

      - name: Install Google Chrome
        run: choco install googlechrome -y

      - name: Set up Chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: Install Tesseract, Ghostscript, GhostPCL, ImageMagick
        run: choco install tesseract ghostscript imagemagick -y

      - name: Check ImageMagick version
        run: magick -version